############################
## CHANGE THESE
############################

baseURL: "https://services.quelltext.eu"
title: services.quelltext.eu

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-gb"
enableRobotsTXT: true

copyright:  '[services.quelltext.eu](https://services.quelltext.eu) by [Nicco Kunzmann](https://github.com/niccokunzmann/) is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'
