############################
## CHANGE THESE
############################

baseURL: "https://niccokunzmann.github.io/services.quelltext.eu"
title: services.quelltext.eu

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
