############################
## Author
############################

author:
  name: Nicco Kunzmann
  image: author.jpg
  greeting: "Open-source web services self-hosted."
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/niccokunzmann/
  # - link: https://github.com/niccokunzmann/services.quelltext.eu#readme
  # - website: 
  # - x-twitter: 
  - mastodon: https://toot.wales/@niccokunzmann
  # - linkedin: 
  # - instagram: 
  # - reddit: 
  - telegram: +447726466688
  # - whatsapp: 
  - signal: +447726466688
  # - codepen: 
  # - dev: 
  - email: niccokunzmann@rambler.ru
  # - discord: 
  # - orcid: 
  # - slack: 
  - stack-overflow: https://stackoverflow.com/users/1320237/user
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: services.quelltext.eu
description: "Open-Source services hosted by Nicco Kunzmann"
images:
  - author.jpg
